import './style/index.scss';
// import './index.css';
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);
export { default as Button } from './components/Button/Button';
export { default as Alert } from './components/Alert/Alert';
export { default as Menu } from './components/Menu/index';
export { default as Tabs } from './components/Tabs';
export { default as Icon } from './components/Icon/Icon';
export { default as Input } from './components/Input/Input';
export { default as AutoComplete } from './components/AutoComplete/AutoComplete';
export { default as Upload } from './components/Upload/Upload';
export { default as Progress } from './components/Progress/Progress';
export { default as Select } from './components/Select/Select';
